# -*- coding: utf-8 -*-
"""monte_carlo_pi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1__UtNgFI7rZfMtAS8gp2AgMZvAtP0TtI
"""

import random
import numpy as np
import matplotlib.pyplot as plt

# Number of random points to generate
N = 2000

# Counter for points that fall inside the quarter circle
count_inside = 0

# Stores the estimated value of pi after each iteration
pi_estimates = []

# Coordinates of all generated points
x = []
y = []

# Coordinates split by whether the point landed inside or outside the quarter circle
x_inside = []
y_inside = []
x_outside = []
y_outside = []

for i in range(1, N + 1):
    # Generate a random point (x, y) inside the unit square [0,1] x [0,1]
    random_x = random.random()
    random_y = random.random()

    x.append(random_x)
    y.append(random_y)

    # Check if the point falls inside the quarter circle of radius 1
    if np.sqrt(random_x**2 + random_y**2) <= 1:
        count_inside += 1
        x_inside.append(random_x)
        y_inside.append(random_y)
    else:
        x_outside.append(random_x)
        y_outside.append(random_y)

    # Estimate pi using the ratio of points inside the quarter circle
    # (area of quarter circle / area of square = pi/4)
    pi_estimate = 4 * count_inside / i
    pi_estimates.append(pi_estimate)

# Number of iterations, used as the x-axis for the convergence plot
iterations = list(range(1, N + 1))


N = 2000
final_pi = pi_estimates[-1]
error_abs = abs(np.pi - final_pi)
print(f'The final estimated value of pi is {final_pi}')
print(f'The absolute error of the estimation is {error_abs}')

fig, axes = plt.subplots(1, 2, figsize=(12, 6))

# Left: convergence of the pi estimate
axes[0].plot(iterations, pi_estimates, color='red', label='Estimate of $\pi$')
axes[0].axhline(y=np.pi, color='black', linewidth=1, label='$\pi$')
axes[0].set_xlabel('Number of iterations')
axes[0].set_ylabel('Estimated value of $\pi$ at each iteration')
axes[0].set_title(f'Estimation of $\pi$ for {N} points')
axes[0].legend()
axes[0].grid()

# Right: spatial distribution of points inside vs outside the quarter circle
axes[1].scatter(x_inside, y_inside, color='blue', s=1, label='Inside quadrant')
axes[1].scatter(x_outside, y_outside, color='red', s=1, label='Outside quadrant')
axes[1].set_title('Spatial Distribution of Samples')
axes[1].legend()

plt.tight_layout()
plt.show()